Collision prevention
Team319/frc319-2019 pull request #14
Opened 2019-02-24 20:00 UTC by jojobean23

Addition of code to prevent the collision of the BBA and Carriage

2019-02-24 21:27 UTC, joshua-robotics approved these changes
I looked through the changes. All changes appear to be good to merge.

2019-02-26 16:00 UTC, tytremblay requested changes

2019-02-26 16:00 UTC, tytremblay commented on src/main/java/org/usfirst/frc/team319/robot/subsystems/BBArm.java
> +  private int homePosition = -500;
I think this should remain 0.

2019-02-26 16:00 UTC, tytremblay commented on src/main/java/org/usfirst/frc/team319/robot/subsystems/BBArm.java
> +    boolean elevatorInterfering = elevatorPosition < elevatorSafePosition;
we never update `elevatorPosition` before checking it here.

2019-02-26 16:28 UTC, tytremblay approved these changes

2019-02-26 16:29 UTC, merged